version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/certs/:/etc/nginx/ssl/
      - nginx_log:/log/nginx
    ports:
      - "80:80"
      - "443:443"
    # env_file:
    #   - .env
    # depends_on:
    # - backend
    restart: always
    networks:
      - ProjectU

  # backend:
  #   image:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo_data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - ProjectU

networks:
  ProjectU:
    driver: bridge

volumes:
  nginx_log:
    driver: local
  mongo_data:
    driver: local
